### ISSUE TITLE
Property "more actions" ellipses not working

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-AdvancedResourceTemplate#1]
When I click on the ellipses on the right side of the value input interface nothing happens. I think this was true for Omeka 3.1 but with the introduction of [value annotations](https://forum.omeka.org/t/value-annotation-not-available/15063) the issue became apparent to me.

When the AdvancedResourceTemplate module (v 3.3.4.12.5) nothing happens when I click on the ellipses (also no Javascript error):
![image](https://user-images.githubusercontent.com/101820/165375442-f2c3a98d-e50f-42d1-b04b-c29f629616e1.png)

When I disable this module, the "more actions" do show when clicked (and thus can be used!):
![image](https://user-images.githubusercontent.com/101820/165375509-6c04618d-78db-4e92-9106-17c3652e3127.png)

**Comment by MarieGuerinel** [comment]
Hello,
I encounter a similar problem: I can add an annotation but to show it on public side, I have to deactivate Advanced Resource Template. With an older version of Advanced Resource Template, the "bubble" for annotation was not showing. With the last release, it works on admin side but not public side.
My installation :
Omeka S version 3.2.1
Advanced Resource Template version 3.3.4.13.1
Thank you in advance Daniel,
Marie

**Comment by sinanatra** [comment]
Hello i also encountered a similar problem. When i activate the module (version 3.3.4.13.1) i cannot see if items have annotations in the view page.

module activated:
![Screenshot 2022-07-14 at 11 06 06](https://user-images.githubusercontent.com/20107875/178946202-928cee49-5a07-4414-8c08-5522302c7e37.png)

module deactivated:
![Screenshot 2022-07-14 at 11 05 59](https://user-images.githubusercontent.com/20107875/178946193-faf8e13f-740b-4135-86bd-0e81d02b0265.png)

**Comment by sinanatra** [comment]
the same issue occurs in version _3.3.4.14_

**Comment by Daniel-KM** [comment]
Thanks it is fixed in last version (3.3.4.16.
