### ISSUE TITLE
how to configure it with custom data type?

### ISSUE THREAD

**Issue by sinanatra** [Daniel-KM/Omeka-S-module-AdvancedResourceTemplate#2]
Hello, i would like to make the module work with the custom data types i use.
In the resource template i select the specific data type (e.g. [the one i created](https://github.com/sinanatra/NestedDataTypes)), and in the default value i would input: 

```
{
    "type": "nesteddatatype#crm:E54_Dimension",
    "@value": [
        {
            "@type": "crm:E54_Dimension",
            "crm:P90_has_value": [
                {
                    "@value": "63"
                }
            ]
        }
    ],
    "is_public": true
}
```
But compared to the literal, uri, or Omeka resource, when accessing the creation of an item nothing is displayed in the interface.
How should i proceed? Is it something i should configure in my module?

**Comment by Daniel-KM** [comment]
This is probably a bug related to this complex type. All other data types are working fine.
