### ISSUE TITLE
Read-only option not working

### ISSUE THREAD

**Issue by j4lib** [Daniel-KM/Omeka-S-module-AdvancedResourceTemplate#5]
First of all: This module is such a great addition to Omeka-S!
However, I tried to set a property to read_only via the option "Property disabled in form", but it does not seem to work. When digging into the code I think I found the culprit. As far as I understand it, the `property_read_only` is either "yes" or 0 in the database. So the following line with `!Number("yes")` or `!Number(0)` will both always be true and the code below it (which makes the property read-only) will never be reached: 
https://github.com/Daniel-KM/Omeka-S-module-AdvancedResourceTemplate/blob/7107db4c0e18e3889892b8b7a6a6a7ea57310776/asset/js/advanced-resource-template-admin.js#L215C68-L215C103
When I change that part of the condition, it seems to work. I am new to Omeka-S so I am not sure if there is a reason for this condition in other contexts.

**Comment by j4lib** [comment]
Fixed with version 3.4.33. Thanks!

**Comment by Daniel-KM** [comment]
I forgot to append the fix #, but you closed.

**Comment by j4lib** [comment]
Do you want me to reopen it?

**Comment by Daniel-KM** [comment]
No, it is fixed.
